Improve testing
CircleCI-Public/gradle-orb pull request #30
Opened 2023-03-16 18:02 UTC by skjolber

The current tests are basically smoke tests and do not test the orb core functionality, i.e. caching.

These bash scripts might require some adjustments, but at least this does test the save/restore cache.

2023-03-26 14:54 UTC, BytesGuy commented
@ryanbourdais Would you be able to take a look into this PR?

2023-03-27 14:23 UTC, ryanbourdais requested changes
Hi @skjolber thanks for this PR, I think these are really great changes to make and get merged in ASAP, but I do have 1 or 2 changes to make, as well as I would like some clarity as to why the filters were changed. Thank you

2023-03-27 14:23 UTC, ryanbourdais commented on .circleci/test-deploy.yml
> +          app_src_directory: sample_app
remove this line, this parameter is unexpected and causes the workflow to fail

2023-03-27 14:23 UTC, ryanbourdais commented on .circleci/test-deploy.yml
> +          filters: *all-tags
same as the filter anchor above

2023-03-27 20:35 UTC, skjolber commented on .circleci/test-deploy.yml
> +filters: &all-tags
The `all-tags` is just a better textual description. I guess it could also be `all-tags-filter`, but `filters` is perhaps a bit generic?

2023-03-27 21:06 UTC, skjolber commented on .circleci/test-deploy.yml
> +filters: &all-tags
Reverted

2023-03-27 21:10 UTC, merged